#!/usr/bin/env node

var utils = require('./utils')
  , push = require('pushover-notifications')
  , system = require('exec-sync')
  , program = require('commander')
  , opts = program;

var p = new push({
	user: process.env["PUSHOVER_USER"],
	token: process.env["PUSHOVER_TOKEN"]
});

PRIORITY = {
	low: -1,
	normal: 0,
	high: 1
};

program.version('0.0.1')
  .option('-m, --message [msg]', 'Message to send')
  .option('-t, --title [title]', 'Title of the message')
  .option('-n, --token [token]', 'Pushover Token to use (uses ENV["PUSHOVER_TOKEN"] or this)')
  .option('-u, --user [user]', 'Pushover user to send to (uses ENV["PUSHOVER_USER"] or this)')
  .option('-p, --priority [priority]', PRIORITY.keys())
  .parse(process.argv);


var notify = function(title, msg, priority_str, token, user) {
	title = title || opts.title;
	msg = msg || opts.message;
	priority_str = priority_str || opts.priority || 'normal';
	p.token = p.token || token || opts.token;
	p.user = p.user || user || opts.user;
	if (!p.token) {
		throw 'Either pass token or set ENV["PUSHOVER_TOKEN"]';
	}
	if (!p.user) {
		throw 'Either pass user or set ENV["PUSHOVER_USER"]';
	}
	var msg = {
		title: title,
		message: msg,
		priority: PRIORITY[priority_str]
	};
	return p.send(msg, function(err, result) {
		if (err) {
			throw err;
		}
		return console.log(result);
	});
}

// run
notify();

