#!/usr/bin/env ruby

require "net/https"
require "thor"

class PushoverMsg < Thor
  
  desc "send", "send a pushover message"
  method_option :message, :type => :string, :required => true, :aliases => "-m"
  def send
    url = URI.parse("https://api.pushover.net/1/messages")
    req = Net::HTTP::Post.new(url.path)
    req.set_form_data({
      :token => ENV['PUSHOVER_TOKEN'],
      :user => ENV['PUSHOVER_USER'],
      :message => options.message,
    })
    res = Net::HTTP.new(url.host, url.port)
    res.use_ssl = true
    res.verify_mode = OpenSSL::SSL::VERIFY_PEER
    res.start { |http| http.request(req) }
  end

  default_task :send
end

# Starts the process if this is being used as a script
# If this is being used as a library this will be skipped
if __FILE__ == $0
  PushoverMsg.start
end

