#!/bin/bash

if [ $("$1" = "--help") || $("$1" = "") ]; then
   echo "sendgmail <subject> <body> <to>"
elif [[ $3 = *@* ]]; then
   echo "Sending email to $3 ..."
   echo "$2" | mail -s "$1" "$3" &
else
   echo "email address invalid"
fi
