// Generated by CoffeeScript 1.6.3
(function() {
	var fs = require('fs')
		,util = require('util');

	Object.prototype.keys = function() {
		var keys = [];
		for (var i in this) {
			if (this.hasOwnProperty(i)) {
				keys.push(i);
			}
		}
		return keys;
	};

	var fileStat = function (file) {
	};

	exports.fileStat = fileStat;

	exports.userHome = function() {
		return process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;
	};

	exports.fileSize = function (file) {
		return fs.lstatSync(file).size;
	};

	exports.isFile = function (item) {
		return fs.lstatSync(item).isFile();
	};

	exports.isDir = function (item) {
		return fs.lstatSync(item).isDirectory();
	};
	

}).call(this);
